### ISSUE TITLE
more of a question than actual issue:

### ISSUE THREAD

**Issue by cotodevel** [lifehackerhansol/blocksds-bootloader#2]
This loader looks perfect for integration into TGDS-multiboot! So I can ensure 100% of NDS devkitARM built payloads (v1, v2 and v3) are supported. Also the license seems perfect for GPLv2 (or GPLv2+ if needed).

But i've got 2 questions before porting it into TGDS-multiboot:

1) Does this boot all kind of NTR / TWL binaries built with v1 (2005, passme v1), v2 (2007, passme v2) and v3 (post 2008) devkitARM homebrew?

2) Does it work on newer loaders (flashcards) & TWL SD (through TWLMenu++ or Unlaunch)?

Related work:
https://bitbucket.org/Coto88/toolchaingenericds-multiboot/issues/9/integrate-open-source-ntr-twl-bootloader

**Comment by lifehackerhansol** [comment]
This isn't my original work, so it *must* be `SPDX-License-Identifier: GPL-2.0-or-later` as identified in most of the files in the source code. (The `.ld` file is MPL-2.0 as seen here: https://github.com/devkitPro/devkitarm-crtls/commit/eac1e8c74f4fc4791c69322d3b93ba51b2eb21a7)

I actually haven't tested v1 or v2. Though:
- This source code originates all the way back to about 2007 (Chishm's bootlib and this is the same code)
- If you ever used devkitPro's nds-hb-menu before, it is the exact same source code. TWiLight Menu++'s bootloaders are also based on devkitPro's code. So if those two can run it, chances are this does as well.

I'm willing to muck with a few example apps, if you have any.

**Comment by cotodevel** [comment]
1)
No, it doesn't work that way (asked a lawyer about this one). GPL is derivative, which allows to spread over the source code as whole, if the original author had mixed licenses (say, BSD-1) at the time he/her made it public & licensed. And you could publish the entire source code as GPL (v2), and other parts could be relicensed as LGPL provided they're in binary format (if I were to use the ARM7/ARM9 payloads here only), because it's derivative. In this repository, the original work predates devkitARM, it comes from NDSLIB as whole, and these sources are already GPL (v2). So it can be relicensed, if I were to base on the original bootstub code instead of this one.

2)

Slot 1 v1 NTR binaries would be basically SLOT2 era and pre DLDI. Most  Neoflash contest homebrew from 2005 era are an example. Same applies for Slot 2 v1 NTR binaries since the passme v1 code was based originally from slot 2 based devices.

Slot 1 v2 NTR binaries would be moonshell1 (pre 2008), lameboy, SnemulDS 0.4 or lower. These have DLDI sections, but the bootstrap code in the ARM9 sections has just 1 mutex (that is, the ARM9 bootstub loops only once waiting for the ARM9 binary's entrypoint to be written from ARM7 (already part of the ARM9 Passme v2 bootstub), then jumps into it). TGDS-MB can boot that kind of homebrew.

Slot 1 v3 NTR/TWL binaries would be moonshell2, gbaemu4ds, gbarunner2, etc (post 2008 homebrew)

3)
OK. I'll just base the loader code on the original sources-- not the modified bits in this repo. For reference, the original bootstub source code can be found on DSOrganize (already GPLv2) or NDSLIB (already GPLv2) & other homebrew pre devkitARM era.

Closing issue.
